"""
modules/kml_export.py
─────────────────────────────────────────────────────────────────────────
Generate KML files for irrigation zone polygons that can be opened in
Google Earth Pro / Google Earth Web.

Polygons are colored by stress level:
  Red    → Severe Deficit  (VWC < 15%)
  Orange → Critical Stress (VWC 15-25%)
  Yellow → Moderate Stress (VWC 25-35%)
  Green  → Adequate        (VWC ≥ 35%)  — outline only
"""

import os
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom.minidom import parseString


# KML colors are in AABBGGRR format (Alpha, Blue, Green, Red)
KML_STYLES = {
    "severe_deficit":  {"fill": "cc1400ef", "outline": "ff1400ef", "label": "Severe Deficit"},
    "critical_stress": {"fill": "cc1673f9", "outline": "ff1673f9", "label": "Critical Stress"},
    "moderate_stress": {"fill": "cc08b3ea", "outline": "ff08b3ea", "label": "Moderate Stress"},
    "adequate":        {"fill": "335ec522", "outline": "ff5ec522", "label": "Adequate"},
}


def generate_kml(zones: list, date_str: str, farm_boundaries=None) -> str:
    """
    Build a KML document with irrigation zone polygons.

    Parameters
    ----------
    zones : list of dicts from irrigation_zones.build_zone_polygons()
    date_str : str, the imagery date (for labeling)
    farm_boundaries : optional GeoJSON FeatureCollection of farm outlines

    Returns
    -------
    KML XML string
    """
    kml = Element("kml", xmlns="http://www.opengis.net/kml/2.2")
    doc = SubElement(kml, "Document")
    SubElement(doc, "name").text = f"Irrigation Zones — {date_str}"
    SubElement(doc, "description").text = (
        f"Predicted irrigation needs from Sentinel-2 imagery ({date_str}). "
        f"Generated by Chinhoyi IrrigAlert System."
    )

    # ─── Styles ───
    for level, style in KML_STYLES.items():
        st = SubElement(doc, "Style", id=f"style_{level}")
        ps = SubElement(st, "PolyStyle")
        SubElement(ps, "color").text = style["fill"]
        SubElement(ps, "outline").text = "1"
        ls = SubElement(st, "LineStyle")
        SubElement(ls, "color").text = style["outline"]
        SubElement(ls, "width").text = "2"

    # Farm outline style
    st = SubElement(doc, "Style", id="style_farm_outline")
    ps = SubElement(st, "PolyStyle")
    SubElement(ps, "fill").text = "0"
    ls = SubElement(st, "LineStyle")
    SubElement(ls, "color").text = "ff00ff00"  # green
    SubElement(ls, "width").text = "2"

    # ─── Farm Boundaries Folder ───
    if farm_boundaries:
        folder = SubElement(doc, "Folder")
        SubElement(folder, "name").text = "Farm Boundaries"
        for feat in farm_boundaries.get("features", []):
            name = feat.get("properties", {}).get("Name", "Farm")
            geom = feat["geometry"]
            if geom["type"] == "Polygon":
                ring = geom["coordinates"][0]
            elif geom["type"] == "MultiPolygon":
                ring = geom["coordinates"][0][0]
            else:
                continue

            pm = SubElement(folder, "Placemark")
            SubElement(pm, "name").text = name
            SubElement(pm, "styleUrl").text = "#style_farm_outline"
            poly = SubElement(pm, "Polygon")
            SubElement(poly, "altitudeMode").text = "clampToGround"
            outer = SubElement(poly, "outerBoundaryIs")
            lr = SubElement(outer, "LinearRing")
            coord_str = " ".join(f"{c[0]},{c[1]},0" for c in ring)
            SubElement(lr, "coordinates").text = coord_str

    # ─── Irrigation Zones Folder ───
    folder = SubElement(doc, "Folder")
    SubElement(folder, "name").text = "Irrigation Zones"
    SubElement(folder, "description").text = "Areas requiring irrigation"

    for zone in zones:
        pm = SubElement(folder, "Placemark")
        SubElement(pm, "name").text = f"{zone['farm_name']} — {zone['label']}"
        SubElement(pm, "description").text = (
            f"Farm: {zone['farm_name']}\n"
            f"Status: {zone['label']}\n"
            f"Mean VWC: {zone['mean_vwc']}%\n"
            f"Pixels: {zone['pixel_count']}\n"
            f"Area: {zone['area_ha']} ha"
        )
        SubElement(pm, "styleUrl").text = f"#style_{zone['stress_level']}"

        poly = SubElement(pm, "Polygon")
        SubElement(poly, "altitudeMode").text = "clampToGround"
        outer = SubElement(poly, "outerBoundaryIs")
        lr = SubElement(outer, "LinearRing")
        coord_str = " ".join(
            f"{c[0]},{c[1]},0" for c in zone["polygon_coords"]
        )
        SubElement(lr, "coordinates").text = coord_str

    # Prettify
    raw = tostring(kml, encoding="unicode")
    return parseString(raw).toprettyxml(indent="  ")


def save_kml(kml_str: str, filepath: str) -> str:
    """Save KML string to a file."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(kml_str)
    return filepath
